#stef.tmp:
#  config:
#    toolbar:
#      - [name: "basicitems", items: ["source"]]
#      - [name: "basicstyles", items: ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']]
#    uiColor: '#ffffff'
parameters:
    stef_simple_cms.twig.asset_exists_extension.class: "Stef\\SimpleCmsBundle\\Twig\\Extension\\AssetExistsExtension"
    stef.slugifier.class: "Stefanius\\Slugifier\\Manipulators\\SlugManipulator"
    stef.fullpath_slugifier.class: "Stef\\SlugManipulation\\Manipulators\\FullpathSlugManipulator"
    stef_simple_cms.reflection.class: "Stef\\SimpleCmsBundle\\Reflection\\ReflectionService"
    stef_simple_cms.dictionary_manager.class: "Stef\\SimpleCmsBundle\\Manager\\DictionaryManager"

services:
    stef.slugifier:
        class: %stef.slugifier.class%

    stef.fullpath_slugifier:
        class:     %stef.fullpath_slugifier.class%
        arguments: ["@stef.slugifier"]

    stef_simple_cms.reflection:
        class: %stef_simple_cms.reflection.class%

    stef_simple_cms.user_manager:
        class: Stef\SimpleCmsBundle\Manager\UserManager
        arguments: ["@doctrine.orm.entity_manager"]

    stef_simple_cms.news_manager:
        class: Stef\SimpleCmsBundle\Manager\NewsManager
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
            - [setSlugifier, ["@stef.slugifier"]]

    stef_simple_cms.news_list_view:
        class: Stef\SimpleCmsBundle\ListView\NewsListView

    stef_simple_cms.default_list_view:
        class: Stef\SimpleCmsBundle\ListView\DefaultListView

    stef_simple_cms.dictionary_list_view:
        class: Stef\SimpleCmsBundle\ListView\DictionaryListView

    stef_simple_cms.page_list_view:
        class: Stef\SimpleCmsBundle\ListView\PageListView

    stef_simple_cms.list_view_service:
        class: Stef\SimpleCmsBundle\ListView\ListViewService
        calls:
            - [addView, [news, "@stef_simple_cms.news_list_view"]]
            - [addView, [default, "@stef_simple_cms.default_list_view"]]
            - [addView, [dictionary, "@stef_simple_cms.dictionary_list_view"]]
            - [addView, [page, "@stef_simple_cms.page_list_view"]]

    stef_simple_cms.dictionary_manager:
        class: %stef_simple_cms.dictionary_manager.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
            - [setSlugifier, ["@stef.slugifier"]]

    stef_simple_cms.page_manager:
        class: Stef\SimpleCmsBundle\Manager\PageManager
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
            - [setSlugifier, ["@stef.slugifier"]]

    stef_simple_cms.form_factory:
        class: Stef\SimpleCmsBundle\Form\FormFactory
        arguments: ["@stef_simple_cms.reflection", "@form.factory"]

    stef_simple_cms.entity_mapper:
        class: Stef\SimpleCmsBundle\EntityMapper\Mapper
        calls:
            - [addNewMapping, ["News", "StefSimpleCmsBundle", "Stef\\SimpleCmsBundle\\Entity", "@stef_simple_cms.news_manager", "Stef\\SimpleCmsBundle\\Form\\NewsType"]]
            - [addNewMapping, ["Page", "StefSimpleCmsBundle", "Stef\\SimpleCmsBundle\\Entity", "@stef_simple_cms.page_manager", "Stef\\SimpleCmsBundle\\Form\\NewsType"]]
            - [addNewMapping, ["Dictionary", "StefSimpleCmsBundle", "Stef\\SimpleCmsBundle\\Entity", "@stef_simple_cms.dictionary_manager", "Stef\\SimpleCmsBundle\\Form\\NewsType"]]
            - [addNewMapping, ["User", "StefSimpleCmsBundle", "Stef\\SimpleCmsBundle\\Entity", "@stef_simple_cms.user_manager", "Stef\\SimpleCmsBundle\\Form\\NewsType"]]

    stef_simple_cms.crud_renderer:
        class: Stef\SimpleCmsBundle\Crud\DefaultCrudRenderer
        arguments: ["@templating", "@router"]

    stef_simple_cms.crud_actions:
        class: Stef\SimpleCmsBundle\Crud\DefaultCrudActions
        arguments: ["@stef_simple_cms.entity_mapper", "@stef_simple_cms.crud_renderer", "@stef_simple_cms.form_options", "@stef_simple_cms.form_factory", "@stef_simple_cms.list_view_service"]

    stef_simple_cms.twig.asset_exists_extension:
        class: '%stef_simple_cms.twig.asset_exists_extension.class%'
        arguments: ['@kernel']
        tags:
          - { name: twig.extension }

    stef_key_value.to_array:
        class: Stef\KeyValueManipulation\Manipulators\KeyValueToArrayManipulator
        arguments: [':', ';']

    stef_key_value.to_json:
        class: Stef\KeyValueManipulation\Manipulators\KeyValueToJsonManipulator
        arguments: [':', ';']

    stef_key_value.to_parameterbag:
        class: Stef\KeyValueManipulation\Manipulators\KeyValueToParameterBagManipulator
        arguments: [':', ';']

    stef_simple_cms.key_value_parser:
        class: Stef\SimpleCmsBundle\KeyValueParser\Parser
        arguments: ['@stef_key_value.to_array', '@stef_key_value.to_json', '@stef_key_value.to_parameterbag']