parameters:
    stef_simple_cms.twig.asset_exists_extension.class: "Stefanius\\SimpleCmsBundle\\Twig\\Extension\\AssetExistsExtension"
    stef.slugifier.class: "Stefanius\\Slugifier\\Manipulators\\SlugManipulator"
    stef.fullpath_slugifier.class: "Stefanius\\SlugManipulation\\Manipulators\\FullpathSlugManipulator"
    stef_simple_cms.reflection.class: "Stefanius\\SimpleCmsBundle\\Reflection\\ReflectionService"
    stef_simple_cms.dictionary_manager.class: "Stefanius\\SimpleCmsBundle\\Manager\\DictionaryManager"

services:
    stef.slugifier:
        class: %stef.slugifier.class%

    stef.fullpath_slugifier:
        class:     %stef.fullpath_slugifier.class%
        arguments: ["@stef.slugifier"]

    stef_simple_cms.reflection:
        class: %stef_simple_cms.reflection.class%

    stef_simple_cms.user_manager:
        class: Stefanius\SimpleCmsBundle\Manager\UserManager
        arguments: ["@doctrine.orm.entity_manager"]

    stef_simple_cms.news_manager:
        class: Stefanius\SimpleCmsBundle\Manager\NewsManager
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
            - [setSlugifier, ["@stef.slugifier"]]

    stef_simple_cms.news_list_view:
        class: Stefanius\SimpleCmsBundle\ListView\NewsListView

    stef_simple_cms.default_list_view:
        class: Stefanius\SimpleCmsBundle\ListView\DefaultListView

    stef_simple_cms.dictionary_list_view:
        class: Stefanius\SimpleCmsBundle\ListView\DictionaryListView

    stef_simple_cms.page_list_view:
        class: Stefanius\SimpleCmsBundle\ListView\PageListView

    stef_simple_cms.list_view_service:
        class: Stefanius\SimpleCmsBundle\ListView\ListViewService
        calls:
            - [addView, [news, "@stef_simple_cms.news_list_view"]]
            - [addView, [default, "@stef_simple_cms.default_list_view"]]
            - [addView, [dictionary, "@stef_simple_cms.dictionary_list_view"]]
            - [addView, [page, "@stef_simple_cms.page_list_view"]]

    stef_simple_cms.dictionary_manager:
        class: %stef_simple_cms.dictionary_manager.class%
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
            - [setSlugifier, ["@stef.slugifier"]]

    stef_simple_cms.page_manager:
        class: Stefanius\SimpleCmsBundle\Manager\PageManager
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
            - [setSlugifier, ["@stef.slugifier"]]

    stef_simple_cms.entity_mapper:
        class: Stefanius\SimpleCmsBundle\EntityMapper\Mapper
        calls:
            - [addNewMapping, ["News", "StefSimpleCmsBundle", "Stefanius\\SimpleCmsBundle\\Entity", "@stef_simple_cms.news_manager", "Stefanius\\SimpleCmsBundle\\Form\\NewsType"]]
            - [addNewMapping, ["Page", "StefSimpleCmsBundle", "Stefanius\\SimpleCmsBundle\\Entity", "@stef_simple_cms.page_manager", "Stefanius\\SimpleCmsBundle\\Form\\NewsType"]]
            - [addNewMapping, ["Dictionary", "StefSimpleCmsBundle", "Stefanius\\SimpleCmsBundle\\Entity", "@stef_simple_cms.dictionary_manager", "Stefanius\\SimpleCmsBundle\\Form\\NewsType"]]
            - [addNewMapping, ["User", "StefSimpleCmsBundle", "Stefanius\\SimpleCmsBundle\\Entity", "@stef_simple_cms.user_manager", "Stefanius\\SimpleCmsBundle\\Form\\NewsType"]]

    stef_simple_cms.crud_renderer:
        class: Stefanius\SimpleCmsBundle\Crud\DefaultCrudRenderer
        arguments: ["@templating", "@router"]

    stef_simple_cms.crud_actions:
        class: Stefanius\SimpleCmsBundle\Crud\DefaultCrudActions
        arguments: ["@stef_simple_cms.entity_mapper", "@stef_simple_cms.crud_renderer", "@stef_simple_cms.list_view_service"]

    stef_simple_cms.twig.asset_exists_extension:
        class: '%stef_simple_cms.twig.asset_exists_extension.class%'
        arguments: ['@kernel']
        tags:
          - { name: twig.extension }
